### ISSUE TITLE
Explain todos

### ISSUE THREAD

**Issue by antonshkurenko** [JakeWharton/DrawerBehavior#22]
It's just a reminder, since I visit this repo three-four times a week and still see the todos. It's very interesting to me. Thanks

**Comment by JakeWharton** [comment]
This project is not currently being worked on and its code is not even in a usable state. It's only on GitHub because I was playing around and wanted to show a single person the code. I don't have any plans to continue working on this project at this time.

**Comment by janheinrichmerker** [comment]
@tonyshkurenko You could fork this project and create a library out of it.

**Comment by antonshkurenko** [comment]
I ain't sure I'm able to do that :)

**Comment by janheinrichmerker** [comment]
@tonyshkurenko Sure you can do that. And even if the library never gets finished you'll learn a lot from it. I guess @JakeWharton csn confirm that ;-) When I started my first open source library it helped a lot looking at best practices and comparing code style and API style to other common libraries. Jake's libraries are just perfect so don't hesitate to look at his code and learn from it. That's the whole purpose of open source
